# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161212_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduce',
            field=models.CharField(default=2, max_length=50, verbose_name='\u4ecb\u7ecd'),
            preserve_default=False,
        ),
    ]
