# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161213_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
