# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161214_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u6307\u6325\u6218\u5f79')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('person', models.TextField(max_length=150, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('content', models.TextField(max_length=300, verbose_name='\u4e2a\u4eba\u8bc4\u4ef7')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=15, verbose_name='\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='content',
            field=models.ManyToManyField(to='blog.Person'),
        ),
    ]
