# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161215_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='content',
            new_name='contented',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='content',
            field=models.TextField(max_length=400, verbose_name='\u4e2a\u4eba\u8bc4\u4ef7'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.TextField(max_length=300, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd'),
        ),
    ]
