# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161215_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='contented',
        ),
        migrations.AddField(
            model_name='achievement',
            name='content',
            field=models.TextField(max_length=500, null=True, verbose_name='\u6218\u5f79\u7b80\u4ecb'),
        ),
        migrations.AddField(
            model_name='person',
            name='achievements',
            field=models.ManyToManyField(to='blog.Achievement'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='\u6307\u6325\u6218\u5f79'),
        ),
        migrations.AlterField(
            model_name='person',
            name='content',
            field=models.TextField(max_length=400, null=True, verbose_name='\u4e2a\u4eba\u8bc4\u4ef7'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.TextField(max_length=300, null=True, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd'),
        ),
    ]
