# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161216_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='introduction',
            field=models.CharField(max_length=30, null=True, verbose_name='\u7b80\u4ecb'),
        ),
    ]
