# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_person_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='title',
        ),
    ]
