# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20161216_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.CharField(default=2, max_length=20, verbose_name='\u6307\u6325\u6218\u5f79'),
            preserve_default=False,
        ),
    ]
