# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20161216_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='created',
        ),
    ]
