# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20161219_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='content',
            field=models.TextField(max_length=500, null=True, verbose_name='\u6218\u5f79\u7b80\u4ecb'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
