# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20161219_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='\u788e\u8a00\u788e\u8bed')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%D')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
