# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_speak'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='\u9898\u76ee'),
        ),
    ]
