# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_speak_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
