# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20161220_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('nickname', models.CharField(max_length=20, verbose_name='\u6635\u79f0')),
                ('motto', models.CharField(max_length=20, verbose_name='\u5ea7\u53f3\u94ed')),
                ('birthday', models.CharField(max_length=10, verbose_name='\u751f\u65e5')),
                ('university', models.CharField(max_length=50, verbose_name='\u5927\u5b66')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=20, verbose_name='\u4e13\u4e1a\u6280\u80fd')),
            ],
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills',
            field=models.ManyToManyField(to='blog.Skill'),
        ),
    ]
