# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20161220_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u751f\u6d3b\u76f8\u5173')),
            ],
        ),
        migrations.AddField(
            model_name='aboutme',
            name='lifes',
            field=models.ManyToManyField(to='blog.Life'),
        ),
    ]
