# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20161220_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='titile',
            new_name='title',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
